//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pelipenko220
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
        private static Entities _context;
        public static Entities GetContext()
        {
            if (_context == null)
                _context = new Entities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Авторы> Авторы { get; set; }
        public virtual DbSet<ВыдачаКниги> ВыдачаКниги { get; set; }
        public virtual DbSet<Город> Город { get; set; }
        public virtual DbSet<Жанры> Жанры { get; set; }
        public virtual DbSet<Издательство> Издательство { get; set; }
        public virtual DbSet<ИнформацияОКниге> ИнформацияОКниге { get; set; }
        public virtual DbSet<ИнформацияОЧитателе> ИнформацияОЧитателе { get; set; }
        public virtual DbSet<ПаспортныеДанные> ПаспортныеДанные { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
    }
}
