//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pelipenko220
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class библEntities1 : DbContext
    {
        public библEntities1()
            : base("name=библEntities1")
        {
        }

        private static библEntities1 _context;
    public static библEntities1 GetContext()
        {
            if (_context == null)
                _context = new библEntities1();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Авторы> Авторы { get; set; }
        public virtual DbSet<ВыдачаКниги> ВыдачаКниги { get; set; }
        public virtual DbSet<Город> Город { get; set; }
        public virtual DbSet<Жанры> Жанры { get; set; }
        public virtual DbSet<Издательство> Издательство { get; set; }
        public virtual DbSet<ИнформацияОКниге> ИнформацияОКниге { get; set; }
        public virtual DbSet<ИнформацияОЧитателе> ИнформацияОЧитателе { get; set; }
        public virtual DbSet<ПаспортныеДанные> ПаспортныеДанные { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
    }
}
