//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pelipenko220
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
        private static Entities _context;
        public static Entities GetContext()
        {
            if (_context == null)
                _context = new Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Авторы> Авторы { get; set; }
        public DbSet<ВыдачаКниги> ВыдачаКниги { get; set; }
        public DbSet<Город> Город { get; set; }
        public DbSet<Жанры> Жанры { get; set; }
        public DbSet<Издательство> Издательство { get; set; }
        public DbSet<ИнформацияОКниге> ИнформацияОКниге { get; set; }
        public DbSet<ИнформацияОЧитателе> ИнформацияОЧитателе { get; set; }
        public DbSet<ПаспортныеДанные> ПаспортныеДанные { get; set; }
        public DbSet<Пользователь> Пользователь { get; set; }
    }
}
