//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pelipenko220
{
    using System;
    using System.Collections.Generic;
    
    public partial class ВыдачаКниги
    {
        public int КодВыдачи { get; set; }
        public int ИнвентарныйНомер { get; set; }
        public int НомерБилета { get; set; }
        public System.DateTime ДатаВыдачи { get; set; }
        public Nullable<System.DateTime> ДатаВозврата { get; set; }
    
        public virtual ИнформацияОКниге ИнформацияОКниге { get; set; }
        public virtual ИнформацияОЧитателе ИнформацияОЧитателе { get; set; }
    }
}
