//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pelipenko220
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИнформацияОКниге
    {
        public ИнформацияОКниге()
        {
            this.ВыдачаКниги = new HashSet<ВыдачаКниги>();
            this.Авторы = new HashSet<Авторы>();
            this.Жанры = new HashSet<Жанры>();
        }
    
        public int ИнвентарныйНомер { get; set; }
        public string Название { get; set; }
        public int КодИздательства { get; set; }
        public int ГодИздания { get; set; }
        public int КолвоСтраниц { get; set; }
        public Nullable<double> Цена { get; set; }
        public string Фото { get; set; }
    
        public virtual ICollection<ВыдачаКниги> ВыдачаКниги { get; set; }
        public virtual Издательство Издательство { get; set; }
        public virtual ICollection<Авторы> Авторы { get; set; }
        public virtual ICollection<Жанры> Жанры { get; set; }
    }
}
