//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pelipenko220
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИнформацияОКниге
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ИнформацияОКниге()
        {
            this.ВыдачаКниги = new HashSet<ВыдачаКниги>();
        }
    
        public int ИнвентарныйНомер { get; set; }
        public string Название { get; set; }
        public Nullable<int> КодАвтора { get; set; }
        public Nullable<int> КодЖанра { get; set; }
        public int КодИздательства { get; set; }
        public int ГодИздания { get; set; }
        public int КолвоСтраниц { get; set; }
        public Nullable<double> Цена { get; set; }
        public string Фото { get; set; }
    
        public virtual Авторы Авторы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ВыдачаКниги> ВыдачаКниги { get; set; }
        public virtual Жанры Жанры { get; set; }
        public virtual Издательство Издательство { get; set; }
    }
}
