//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pelipenko220
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПаспортныеДанные
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ПаспортныеДанные()
        {
            this.ИнформацияОЧитателе = new HashSet<ИнформацияОЧитателе>();
        }
    
        public int КодПаспорта { get; set; }
        public string КемВыдан { get; set; }
        public int Серия { get; set; }
        public int Номер { get; set; }
        public string КодПодразделения { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ИнформацияОЧитателе> ИнформацияОЧитателе { get; set; }
    }
}
